### ISSUE TITLE
Clarification on Model Weights and Request for Training Code Release

### ISSUE THREAD

**Issue by wzbos-token** [Kiteretsu77/This_and_That_VDM#1]
Hello, thank you very much for the excellent work you've done. I noticed that the download links for the V1.0 and V1.1 model weights seem to be the same, but it appears that the ckpt files are missing. Could you please confirm?Could you please release the training code as soon as possible?

**Comment by Kiteretsu77** [comment]
Thanks for the feedback!  The V1.1 link is here:https://huggingface.co/HikariDawn/This-and-That-1.1
The V1.0 link is here: https://huggingface.co/HikariDawn/This-and-That-1.0.
The training code is always available under the "train_code/" folder, but I may need to manage the curation folder.

**Comment by taeyeopl** [comment]
@Kiteretsu77 I am interested in reproducing the results in Table 3 (Simulation Rollout Qualitative Comparison) of the main paper. Do you plan to release the IssacGym training and evaluation code? It would be very helpful.

**Comment by Kiteretsu77** [comment]
@taeyeopl Yes, we planned to release that but likely until the acceptance of the paper (End of Jan for ICRA). Further, we need time to organize the code. That part requires 5 external packages (including some setting specialized for our lab) to install, which may be time consuming to organize. I think that I will start preparing that part at the end of Decemeber after all my school stuff is done for this semester.

**Comment by taeyeopl** [comment]
@Kiteretsu77 Thanks, I hope everything goes well. I look forward to all the code updates.

**Comment by taeyeopl** [comment]
Do you have plans to release the simulation code, which includes training and evaluation?

**Comment by Kiteretsu77** [comment]
I am trying to push my other author on it, but currently I graduated, so everything is slow for the contact.
